<?php
/**
 * Landing Page Configuration
 * Auto-generated by NovaCommerce
 *
 * DO NOT EDIT - This file is automatically updated during deployment
 */

// NovaCommerce API Configuration
$apiUrl = 'https://commerce.novaweb.dev/api/offers/hand-warmers/public';
$apiKey = 'lk_0544eff272f4a719fb443ff363d9f9d8f61d3ff207e0083f';
$checkoutApiUrl = 'https://commerce.novaweb.dev/api/checkout';

// Offer identifier
$offerSlug = 'hand-warmers';

// Cache settings (in seconds)
$cacheEnabled = true;
$cacheTtl = 300; // 5 minutes

// Debug mode
$debug = false;